# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib zikaABM
run_simulation <- function(step, final_t, NH, NM, microProbs, burnin, seed, pars) {
    .Call('zikaABM_run_simulation', PACKAGE = 'zikaABM', step, final_t, NH, NM, microProbs, burnin, seed, pars)
}

